---

- name: Remove the old configuration directory
  file: 
    path: ~/configs/{{ ansible_host }} 
    state: absent

- name: Create the old configuration directory
  file: 
    path: ~/configs/{{ ansible_host }}
    state: directory

- name: IGP configuration
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - igp
  loop:
    - interfaces.conf
    - ospf.conf
    - mpls.conf
  loop_control:
    extended: yes
