---
# tasks file for roles/base

- name: Create host specific configuration directory
  file: path=~/configs/{{ ansible_host }} state=directory

- file: path=~/configs/{{ ansible_host }}/interfaces.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/ospf.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/mpls.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/{{ ansible_host }}.conf state=absent

- name: interface Configuration
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - igp
  with_items:
    - interfaces.conf

- name: OSPF Configuration
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - ospf
    - igp
  with_items:
    - ospf.conf

- name: MPLS Configuration
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - mpls
    - igp
  with_items:
    - mpls.conf