interfaces:
  - name: eth1
    ipv4: 
      ip: 192.168.100.13
      netmask: 24
  - name: eth2
    ipv4: 
      ip: 100.64.3.1
      netmask: 31
    ipv6:
      ip: fd02:3::1
      netmask: 127 
loopback:
  ipv4: 
    ip: 3.3.3.3
    netmask: 24
  ipv6:
    ip: "fddd:3::1"
    netmask: 64
bgp:
  id: 3.3.3.3
  asn: 30003
  sessions:
    ipv4:
      - peer_ip: 100.64.3.0
        peer_asn: 4200000666
    ipv6:
      - peer_ip: fd02:3::0
        peer_asn: 4200000666