interfaces:
  - name: eth1
    ipv4: 
      ip: 192.168.100.11
      netmask: 24
  - name: eth2
    ipv4: 
      ip: 100.64.1.1
      netmask: 31
    ipv6:
      ip: fd02:1::1
      netmask: 127 
loopback:
  ipv4: 
    ip: 1.1.1.1
    netmask: 24
  ipv6:
    ip: "fddd:1::1"
    netmask: 64
bgp:
  id: 1.1.1.1
  asn: 30001
  sessions:
    ipv4:
      - peer_ip: 100.64.1.0
        peer_asn: 35280
    ipv6:
      - peer_ip: fd02:1::0
        peer_asn: 35280