interfaces:
  - name: eth1
    ipv4: 
      ip: 192.168.100.12
      netmask: 24
  - name: eth2
    ipv4: 
      ip: 100.64.2.1
      netmask: 31
    ipv6:
      ip: fd02:2::1
      netmask: 127 
loopback:
  ipv4: 
    ip: 2.2.2.2
    netmask: 24
  ipv6:
    ip: "fddd:2::1"
    netmask: 64
bgp:
  id: 2.2.2.2
  asn: 30002
  sessions:
    ipv4:
      - peer_ip: 100.64.2.0
        peer_asn: 35280
    ipv6:
      - peer_ip: fd02:2::0
        peer_asn: 35280