---

my_ipv4_loopback: 10.200.0.1
my_ipv6_loopback: fd00::1
ibgp_peers:
  - name: vqfx2
    ipv4: 10.200.0.2
    ipv6: fd00::2
  - name: vqfx3
    ipv4: 10.200.0.3
    ipv6: fd00::3
  - name: vqfx4
    ipv4: 10.200.0.4
    ipv6: fd00::4
