igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.1
      netmask: 32
    ipv6:
      local_ip: fd00::1
      netmask: 128    
    name: lo0
    vlan: 0
  neighbors:
  - interface: xe-0/0/0
    peer: vqfx2
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.0
        netmask: 31
        peer_ip: 10.0.0.1
      ipv6:
        local_ip: fd01::0
        netmask: 127
        peer_ip: fd01::1
  - interface: xe-0/0/1
    peer: vqfx4
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.7
        netmask: 31
        peer_ip: 10.0.0.6
      ipv6:
        local_ip: fd01::7
        netmask: 127
        peer_ip: fd01::6
  - interface: xe-0/0/3
    peer: vqfx3
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.8
        netmask: 31
        peer_ip: 10.0.0.9
      ipv6:
        local_ip: fd01::8
        netmask: 127
        peer_ip: fd01::9
