---

l3vpn_vrf_local:
  - 'vpn-15'

# Netbox via customer_interfaces
customer_interfaces:
- asn: 30001
  cid: xx-multi-01
  interface: xe-0/0/2
  name: Customer 1
  patch_panel: PP-XX
  slug: customer-1
  speed: 10G
  type: customer-multi
  vlans:
  - id: 0
    ipv4:
      local_ip: 100.64.1.0
      netmask: 31
      peer_ip: 100.64.1.1
    ipv6:
      local_ip: fd02:1::0
      netmask: 127
      peer_ip: fd02:1::1
    vrf: vpn-15

# Voir ou on le stock (acnet? -> manque vrf)
l3vpn_sessions:
- vrf: vpn-15
  sessions:
  - name: Customer 1
    slug: customer-1
    local_asn: 12345
    peer_asn: 30001
    ipv4:
      peer_ip: 100.64.1.1
    ipv6:
      peer_ip: fd02:1::1