---

l3vpn_vrf_local:
  - 'vpn-aws-cust-1'

customer_interfaces:
- asn: 30001
  cid: xx-multi-01
  interface: xe-0/0/2
  name: Customer 1
  patch_panel: PP-XX
  slug: customer-1
  speed: 10G
  type: customer-multi
  vlans:
  - id: 0
    ipv4:
      local_ip: 100.64.1.0
      netmask: 31
      peer_ip: 100.64.1.1
    ipv6:
      local_ip: 3000:1::0
      netmask: 127
      peer_ip: 3000:1::1
    vrf: vpn-aws-cust-1

# Voir ou on le stock (acnet)
l3vpn_sessions:
- vrf: vpn-aws-cust-1
  sessions:
  - name: Customer 1
    slug: customer-1
    peer_asn: 30001
    ipv4:
      peer_ip: 100.64.1.1
    ipv6:
      peer_ip: 3000:1::1