igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.3
      netmask: 32
    name: lo0
    vlan: 0
  neighbors:
  - interface: xe-0/0/0
    peer: vqfx2
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.2.1
        netmask: 31
        peer_ip: 10.0.2.0
  - interface: xe-0/0/1
    peer: vqfx1
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.3.0
        netmask: 31
        peer_ip: 10.0.3.1
