igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.3
      netmask: 32
    ipv6:
      local_ip: fd00::3
      netmask: 128    
    name: lo0
    vlan: 0
  neighbors:
  - interface: xe-0/0/0
    peer: vqfx4
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.4
        netmask: 31
        peer_ip: 10.0.0.5
      ipv6:
        local_ip: fd01::4
        netmask: 127
        peer_ip: fd01::5
  - interface: xe-0/0/1
    peer: vqfx2
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.3
        netmask: 31
        peer_ip: 10.0.0.2
      ipv6:
        local_ip: fd01::3
        netmask: 127
        peer_ip: fd01::2
  - interface: xe-0/0/3
    peer: vqfx2
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.9
        netmask: 31
        peer_ip: 10.0.0.8
      ipv6:
        local_ip: fd01::9
        netmask: 127
        peer_ip: fd01::8