---

l3vpn_vrf_local:
  - 'vpn-234'

customer_interfaces:
- asn: 30003
  cid: xx-multi-01
  interface: xe-0/0/2
  name: Customer 3
  patch_panel: PP-XX
  slug: customer-3
  speed: 10G
  type: customer-multi
  vlans:
  - id: 0
    ipv4:
      local_ip: 100.64.3.0
      netmask: 31
      peer_ip: 100.64.3.1
    ipv6:
      local_ip: fd02:3::0
      netmask: 127
      peer_ip: fd02:3::1
    vrf: vpn-234

l3vpn_sessions:
- vrf: vpn-234
  sessions:
  - name: Customer 3
    slug: customer-3
    peer_asn: 30003
    ipv4:
      peer_ip: 100.64.3.1
    ipv6:
      peer_ip: fd02:3::1