---


- name: Create host specific configuration directory
  file: path=~/configs/{{ ansible_host }} state=directory

- file: path=~/configs/{{ ansible_host }}/mpls_lsp.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/vrf.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/sessions.conf.part state=absent
- file: path=~/configs/{{ ansible_host }}/{{ ansible_host }}.conf state=absent


- name: LSP
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - l3vpn
  with_items:
    - mpls_lsp.conf

- name: VRF L3VPN Configuration
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - l3vpn
  with_items:
    - vrf.conf

- name: BGP Session customers
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ item }}.part
  tags:
    - l3vpn
  with_items:
    - sessions.conf

# - name: OSPF Configuration
#   template:
#     src={{ item }}.j2
#     dest=~/configs/{{ ansible_host }}/{{ item }}.part
#   tags:
#     - ospf
#   with_items:
#     - ospf.conf