---

- name: Remove the old configuration directory
  file: 
    path: ~/configs/{{ ansible_host }} 
    state: absent

- name: Create the old configuration directory
  file: 
    path: ~/configs/{{ ansible_host }}
    state: directory

- name: L3VPN configuration
  template:
    src={{ item }}.j2
    dest=~/configs/{{ ansible_host }}/{{ ansible_loop.index }}_{{ item }}.part
  tags:
    - l3vpn
  loop:
    - vrf.conf
    - interfaces.conf
    - sessions.conf
  loop_control:
    extended: yes

