igp:
  loopbacks:
  - ipv4:
      local_ip: 10.200.0.2
      netmask: 32
    ipv6:
      local_ip: fd00::2
      netmask: 128    
    name: lo0
    vlan: 0
  neighbors:
  - interface: xe-0/0/0
    peer: vqfx1
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.1
        netmask: 31
        peer_ip: 10.0.0.0
      ipv6:
        local_ip: fd01::1
        netmask: 127
        peer_ip: fd01::0
  - interface: xe-0/0/1
    peer: vqfx3
    speed: 10G
    type: local-core
    vlans:
    - id: 0
      ipv4:
        local_ip: 10.0.0.2
        netmask: 31
        peer_ip: 10.0.0.3
      ipv6:
        local_ip: fd01::2
        netmask: 127
        peer_ip: fd01::3
