---

l3vpn_connectors:
  'vpn-aws-cust-1':
    - interface: xe-0/0/2

l3vpn_sessions:
- vrf: vpn-aws-cust-1
  sessions:
  - name: AWS
    slug: aws
    peer_asn: 30002
    ipv4:
      peer_ip: 100.64.2.1